import{S as m,i as y}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const h="46322499-d914655ae29712659c6ba744e",g="https://pixabay.com/api/";async function b(e,r=1,n=12){const s=`${g}?key=${h}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${n}`;try{const t=await fetch(s);if(!t.ok)throw new Error("Network response was not ok");return await t.json()}catch(t){throw console.error("Fetching images failed:",t),t}}function w(e){return`
    <a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" width="360" loading="lazy" data-caption="${e.tags}" />
      <div class="info">
        <p><b>Likes:</b> ${e.likes}</p>
        <p><b>Views:</b> ${e.views}</p>
        <p><b>Comments:</b> ${e.comments}</p>
        <p><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </a>
  `}function L(e){const r=document.querySelector(".gallery"),n=e.map(w).join("");r.insertAdjacentHTML("beforeend",n),a.refresh()}function $(){document.querySelector(".gallery").innerHTML=""}let d=1;const S=12,f=document.querySelector("#search-form"),p=f.querySelector("input"),v=document.querySelector(".loader"),a=new m(".gallery a",{captions:!0,captionsData:"data-caption",captionDelay:250});let c;f.addEventListener("submit",q);a.on("show.simplelightbox",()=>{c=document.activeElement,document.body.classList.add("lightbox-open")});a.on("close.simplelightbox",()=>{c&&c.focus(),document.body.classList.remove("lightbox-open")});function q(e){e.preventDefault();const r=p.value.trim();if(!r){l("warning","Please enter a search query!");return}d=1,$(),P(r)}function u(e){v.style.display=e?"block":"none"}function l(e,r){y[e]({title:e.charAt(0).toUpperCase()+e.slice(1),message:r})}async function P(e){u(!0);try{const r=await b(e,d,S);if(r.hits.length===0){l("info","Sorry, no images were found for your search query.");return}L(r.hits),a.refresh(),p.value=""}catch(r){l("error","Something went wrong. Please try again later."),console.error(r)}finally{u(!1)}}
//# sourceMappingURL=index.js.map
